#!/usr/bin/env bash
set -euo pipefail

# ── Prompt for version label ──────────────────────────────────────────────────
read -rp "Version label (e.g. v1.2, sprint-4): " VERSION
if [[ -z "$VERSION" ]]; then
  echo "Error: version label cannot be empty." >&2
  exit 1
fi

echo ""
echo "→ Regenerating app/page.tsx from design.pen …"

# ── Regenerate page.tsx via Claude Code ───────────────────────────────────────
CLAUDE_RAW=$(claude --print \
  "Look at the design.pen file in this project and regenerate app/page.tsx as a landing page. Use Tailwind CSS. Match the layout, naming and structure from the canvas exactly. Only output the updated file — no explanation.")

# Strip markdown code fences if Claude wrapped the output (macOS-compatible awk)
CLAUDE_STRIPPED=$(printf '%s\n' "$CLAUDE_RAW" \
  | awk '/^```/{if(in_block){in_block=0;next}else{in_block=1;next}} in_block{print}')

# If stripping produced nothing (no fences used), fall back to raw output
if [[ -z "$CLAUDE_STRIPPED" ]]; then
  CLAUDE_STRIPPED="$CLAUDE_RAW"
fi

printf '%s\n' "$CLAUDE_STRIPPED" > app/page.tsx.tmp

# Validate the output isn't empty
if [[ ! -s app/page.tsx.tmp ]]; then
  echo "Error: Claude returned an empty file. Aborting." >&2
  rm -f app/page.tsx.tmp
  exit 1
fi

mv app/page.tsx.tmp app/page.tsx
echo "✓ app/page.tsx updated."

# ── Commit ────────────────────────────────────────────────────────────────────
echo ""
echo "→ Committing …"
git add app/page.tsx

git commit -m "design($VERSION): regenerate landing page from design.pen

- Source: design.pen (hero-container canvas)
- Generated by: claude --print
- Version: $VERSION"

echo "✓ Committed."

# ── Push ──────────────────────────────────────────────────────────────────────
echo ""
echo "→ Pushing to origin/$(git rev-parse --abbrev-ref HEAD) …"
git push

echo ""
echo "Done! $VERSION shipped."
